name: campus_flutter
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  connectivity_plus: ^4.0.1
  device_info_plus: ^9.0.2
  dio: ^5.1.2
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_native_splash: ^2.2.19
  flutter_secure_storage: ^8.0.0
  geolocator: ^10.0.0
  hive: ^2.2.3
  http: ^1.2.1
  intl: ^0.19.0
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
  package_info_plus: ^4.0.2
  path_provider: ^2.0.15
  rxdart: ^0.27.7
  shimmer: ^3.0.0
  sliding_up_panel: ^2.0.0+1
  syncfusion_flutter_calendar: ^28.2.9
  syncfusion_flutter_charts: ^28.2.9
  syncfusion_flutter_datepicker: ^28.2.9
  url_launcher: ^6.1.10
  shared_preferences: ^2.1.2
  flutter_riverpod: ^2.3.6
  get_it: ^7.6.0
  collection: ^1.17.1
  timeago: ^3.4.0
  webview_flutter: ^4.2.2
  flutter_launcher_icons: ^0.13.1
  fast_immutable_collections: ^9.1.5
  auto_size_text: ^3.0.0
  icalendar_parser: ^2.0.0
  flutter_osm_plugin: ^1.3.0
  nfc_manager: ^3.3.0
  flutter_html: ^3.0.0-beta.2
  flutter_rating_bar: ^4.0.1
  image_picker: ^1.0.4
  stash: ^5.0.1
  stash_hive: ^5.0.1
  flutter_localizations:
    sdk: flutter
  firebase_messaging: ^15.2.4
  firebase_core: ^3.12.1
  flutter_local_notifications: ^18.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.24.1
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  lints: ^2.1.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/map_styles/
    - assets/images/logos/tum-logo-blue.png
    - assets/images/placeholders/portrait_placeholder.png
    - assets/images/placeholders/news_placeholder.png
    - assets/images/errors/error.png
    - assets/images/errors/error_crop.png
    - assets/images/errors/error_square.png
    - assets/images/tower.png
    - assets/images/campus/campus-freising.jpg
    - assets/images/campus/campus-garching.jpeg
    - assets/images/campus/campus-klinikum.jpg
    - assets/images/campus/campus-olympia.jpg
    - assets/images/campus/campus-stamm.jpeg
