name: Deploy Dev to Firebase App Distribution

on:
  push:
    branches:
      - 'master'
      - 'development'
    paths:
      - '.github/**'
      - 'lib/**'
      - 'ios/**'
      - 'android/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Cache pub dependencies
        uses: actions/cache@v3
        with:
          path: ${{ env.FLUTTER_HOME }}/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: ${{ runner.os }}-pub-

      - name: Cache Gradle and wrapper
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}

      - name: Install Flutter Packages
        run: flutter pub get

      - name: Run build runner
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Build apk
        run: flutter build apk --release
        env:
          ANDROID_KEY_ALIAS: key
          ANDROID_KEYSTORE_FILE: ../release-key.keystore
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}

      - name: Upload apk to GitHub Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: build/app/outputs/apk/release/app-release.apk

      - name: Upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: "1:733151385985:android:383d34852b5f50c589f080"
          serviceCredentialsFileContent: ${{ secrets.GOOGLE_SERVICES_JSON }}
          groups: testers
          file: build/app/outputs/bundle/release/app-release.aab

